name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # or your default branch

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create config file
        run: |
          echo "const emailConfig = {
            PUBLIC_KEY: '${{ secrets.EMAILJS_PUBLIC_KEY }}',
            SERVICE_ID: '${{ secrets.EMAILJS_SERVICE_ID }}',
            TEMPLATE_ID: '${{ secrets.EMAILJS_TEMPLATE_ID }}'
          };" > config.js

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "."

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
